### ISSUE TITLE
Configure & Test Rocket.chat SlackBridge (integraton to mirror slack channels on Rocket.Chat)

### ISSUE THREAD

**Issue by fititnt** [fititnt/chatops-wg#26]

**Comment by fititnt** [comment]
As https://rocket.chat/docs/administrator-guides/import/slack/slackbridge/:

...

![captura de tela de 2018-02-03 20-58-24](https://user-images.githubusercontent.com/812299/35772474-872b3540-0926-11e8-9d44-e67124ba6000.png)

![captura de tela de 2018-02-03 21-04-52](https://user-images.githubusercontent.com/812299/35772481-a53bb262-0926-11e8-8a2f-8a377108a78b.png)

![captura de tela de 2018-02-03 21-02-50](https://user-images.githubusercontent.com/812299/35772479-98099f96-0926-11e8-886d-a7585aadb8cf.png)

**Comment by fititnt** [comment]
humm

```
rocketchat_1          | rocketchat_logger rocketchat_logger.js:278 SlackBridge ➔ Class.error Error attempting to connect to Slack { Error: tunneling socket could not be established, cause=unable to verify the first certificate
rocketchat_1          |   at ClientRequest.onError (/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/tunnel-agent/index.js:176:17)
rocketchat_1          |   at Object.onceWrapper (events.js:315:30)
rocketchat_1          |   at emitOne (events.js:116:13)
rocketchat_1          |   at ClientRequest.emit (events.js:211:7)
rocketchat_1          |   at TLSSocket.socketErrorListener (_http_client.js:387:9)
rocketchat_1          |   at emitOne (events.js:116:13)
rocketchat_1          |   at TLSSocket.emit (events.js:211:7)
rocketchat_1          |   at emitErrorNT (internal/streams/destroy.js:64:8)
rocketchat_1          |   at _combinedTickCallback (internal/process/next_tick.js:138:11)
rocketchat_1          |   at process._tickDomainCallback (internal/process/next_tick.js:218:9)
rocketchat_1          |  code: 'ECONNRESET' }
```

**Comment by fititnt** [comment]
https://github.com/request/tunnel-agent/blob/eb2b1b19e09ee0e6a2b54eb2612755731b7301dc/index.js#L176

```js
  function onError(cause) {
    connectReq.removeAllListeners()

    debug('tunneling socket could not be established, cause=%s\n', cause.message, cause.stack)
    var error = new Error('tunneling socket could not be established, ' + 'cause=' + cause.message)
    error.code = 'ECONNRESET'
    options.request.emit('error', error)
    self.removeSocket(placeholder)
  }
```

**Comment by fititnt** [comment]
I tried to disable valid SSL checking, and it still persists. 

![captura de tela de 2018-02-03 21-33-56](https://user-images.githubusercontent.com/812299/35772824-20554e86-092c-11e8-8e34-1ea8ee33058c.png)

Tried with SlackBridge Out disabled. No change.

![captura de tela de 2018-02-03 21-52-23](https://user-images.githubusercontent.com/812299/35772858-94e60a06-092c-11e8-97ad-b71bfd02a63a.png)

Due to the error message and the lack of complaint from other people, it must be some error on our server. I think I'll retry at another time or ask someone else on our group to test.

**Comment by fititnt** [comment]
Humm, our container cannot `curl -v https://slack.com/api`.

```bash
root@chatopswg:~# docker exec -it rocketchat_rocketchat_1 bash
rocketchat@e2ded707228a:/app/bundle$ curl -v https://slack.com/api
* Hostname was NOT found in DNS cache
*   Trying 45.55.32.60...
* connect to 45.55.32.60 port 1080 failed: Connection refused
* Failed to connect to rocketchat.chatopswg.xyz port 1080: Connection refused
* Closing connection 0
curl: (7) Failed to connect to rocketchat.chatopswg.xyz port 1080: Connection refused
```
